### ISSUE TITLE
`devspace upgrade` downloading a GitHub json file

### ISSUE THREAD

**Issue by abh** [devspace-sh/devspace#2520] opened 2023-02-02 09:04 UTC
On MacOS (and arm / m1 architecture):

```
% devspace upgrade
info Downloading newest version...
done Successfully updated to version 6.2.5
info Release note:

## What's Changed
* Cyclic dependency detection by @FabianKramm in https://github.com/devspace-sh/devspace/pull/2492
* Fix local Registry incorrectly used with insecure registry by @lizardruss in https://github.com/devspace-sh/devspace/pull/2494
* Section commands such as devspace run [command] do not work when the k8s cluster is unavailable by @lizardruss in https://github.com/devspace-sh/devspace/pull/2495
* Always use buildkit for local registry by @FabianKramm in https://github.com/devspace-sh/devspace/pull/2499
* docs: Add note on `terminal` container replacement by @ninjaprox in https://github.com/devspace-sh/devspace/pull/2502
* Feature: Add support for InlineManifest blocks in Kubectl deployments by @89luca89 in https://github.com/devspace-sh/devspace/pull/2500 and https://github.com/devspace-sh/devspace/pull/2503
* docs: Add back runtime variables page from 5.x. Fix ENG-878 by @89luca89 in https://github.com/devspace-sh/devspace/pull/2510
* Add pull secret configuration for images when upgrading from v5 schemas by @lizardruss in https://github.com/devspace-sh/devspace/pull/2512

## New Contributors
* @ninjaprox made their first contribution in https://github.com/devspace-sh/devspace/pull/2502
* @89luca89 made their first contribution in https://github.com/devspace-sh/devspace/pull/2500

**Full Changelog**: https://github.com/devspace-sh/devspace/compare/v6.2.4...v6.2.5

% devspace version
/Users/ask/bin/devspace: line 1: url:https://api.github.com/repos/devspace-sh/devspace/releases/assets/93304256: No such file or directory

% cat devspace
{"url":"https://api.github.com/repos/devspace-sh/devspace/releases/assets/93304256","id":93304256,"node_id":"RA_kwDOCKbcz84Fj7XA","name":"devspace-darwin-amd64","label":"","uploader":{"login":"github-actions[bot]","id":41898282,"node_id":"MDM6Qm90NDE4OTgyODI=","avatar_url": ...
```

**Comment by 89luca89** [comment] 2023-02-02 09:55
Hi @abh this is a duplicate of #2516 
it's already under investigation

Thanks for reporting!

**Closed by 89luca89** 2023-02-02 09:55 UTC
Labels: kind/bug, bug
