### ISSUE TITLE
devspace dev crashes if devspace_start.sh doesn't have run permissions

### ISSUE THREAD

**Issue by Dador** [devspace-sh/devspace#2436] opened 2022-11-24 09:28 UTC
**What happened?**
If you have have a `devspace_start.sh` without `execute` permission and try to run `devspace dev`, you will get unuseful `[screen is terminating]` message.

Same happens if file `devspace_start.sh` was deleted.

**What did you expect to happen instead?**
Friendly error message or automatic fix (giving execute permissions to `devspace_start.sh`).

**How can we reproduce the bug?** (as minimally and precisely as possible)

```
chmod 0644 devspace_start.sh
devspace dev
```

**Local Environment:**

* DevSpace Version: 6.1.1
* Operating System: mac
* ARCH of the OS: ARM64

**Kubernetes Cluster:**

* Cloud Provider: other
* Kubernetes Version: -

**Comment by pratikjagrut** [comment] 2022-11-25 07:21
Hi, @Dador Thank you for creating this issue.

**Comment by pratikjagrut** [comment] 2022-11-25 07:41
@Dador if the command specified in the `dev.terminal.command` config does not have exec permission then devspace will terminate. If you start your project with `devspace init`, then in the default case the command will `./devspace_start.sh`, which by default should have exec permission but in case they're changed then the command will fail.

The screen is another application we install in the container for a persistent shell session. The command specified in the terminal config will by default run in the screen. In your case, if it's failing then before the screen terminates it'll show an error `sh: ./devspace_start.sh: Permission denied` and then it'll print `[screen is terminating]`. But for some reason before printing the `[screen is terminating]` it'll print multiple blank lines (like pressing an enter key multiple times) IDK why that happens.

I'm not really sure if it's a devspace issue or a screen issue, but we'll try to better log the error or could work on some fallback mechanism. Meanwhile, if you don't want to use the screen then you can disable it.
```
 terminal:
      command: ./devspace_start.sh
      disableScreen: true
```

**Comment by alexandradragodan** [comment] 2022-12-09 09:21
Hey, @Dador 👋 

Thanks for creating this issue!
Does @pratikjagrut's suggestion work for you?

We'd appreciate it if you could confirm.
Thanks!

**Comment by Dador** [comment] 2022-12-09 10:08
@alexandradragodan suggestions are good and it's easy to fix when you know you have this problem, but it's not easy to determine the problem when all you see is `[screen is terminating]`. This issue is a suggestion to somehow make error message more helpful (maybe checking permission before running the script).

**Comment by alexandradragodan** [comment] 2022-12-19 14:50
Ohh, now I got it! @Dador 
That's definitely something we want to improve for our users! 🥇 
 
 Thanks for the suggestion, I'll bring the topic in our internal planning too! 
 
 Have a great day ahead!

**Comment by alexandradragodan** [comment] 2023-03-14 10:39
Hey, @Dador 

A few updates regarding this issue: I tried to set execute permissions on the devspace_start.sh script automatically. Yet, it's not quite possible as we can also have commands in that field to be executed when running devspace dev. So 
giving execute permissions on those, if it s not a file script, would result into some error for those users. 

The error message is, I think, informative enough as it states the cause of the terminal session shutdown too. (see picture below). 

<img width="374" alt="Screenshot 2023-03-14 at 12 37 01" src="https://user-images.githubusercontent.com/115644805/224974724-1d8549af-8180-4fc1-82fb-3c96d61be829.png">

This being said, I would close the issue if that's fine with you. 😄 

Please feel free to open another one if you encounter some issues.

**Closed by alexandradragodan** 2023-03-14 10:39 UTC
Labels: enhancement

**Comment by Dador** [comment] 2023-03-14 12:38
@alexandradragodan maybe it changed, but when I created issue only `[screen is terminating]` was displayed because `screen` seems to cleaned the console before exiting. You can read (comment above)[https://github.com/devspace-sh/devspace/issues/2436#issuecomment-1327115853] for more context (in that comment it says "it'll print multiple blank lines" but I belive it depends on terminal compatibility, if terminal is compatible then it'll remove/clean lines, not just print blank lines).

If it changed and message like in your screenshot is shown then I think it solves the issue.
