### ISSUE TITLE
Parallel build leads to duplicate builds of the same image

### ISSUE THREAD

**Issue by ComaVN** [devspace-sh/devspace#1262] opened 2020-12-14 15:13 UTC
**What happened?**
When running `devspace build` on a project with multiple images, created from the same `Dockerfile`, these images are built twice, without using each other's cached docker image layers.

**What did you expect to happen instead?**
I expect the docker build cache to be used so build times stay low, we don't unnecessarily burden resources needed during build, etc.

**How can we reproduce the bug?** (as minimally and precisely as possible)
[https://github.com/ComaVN/devspace-parallel-build](https://github.com/ComaVN/devspace-parallel-build) (See the readme)

TL;DR: when running `devspace dev`, the 2 containers return different results, because their randomly generated file is different. When running `devspace dev --build-sequential`, the containers return the same result, because they use the same image manifest/layers.

**Local Environment:**

* DevSpace Version: 5.5.0
* Operating System: Ubuntu 20.04.1 LTS
* Deployment method: kubectl apply

**Kubernetes Cluster:**

* Cloud Provider: DevSpace Cloud
* Kubernetes Version: v1.19.4 Client & Server

**Anything else we need to know?**
My actual usecase is a bit more complex: my Dockerfile is multistage, where stage B depends on stage A, container 1 uses stage A and container 2 uses stage B. The behaviour is the same: stage A is built twice.

If it is not feasible to actually fix this (which I can understand) it would be very acceptable to be able to disable parallel builds in `devspace.yaml`

/kind bug

**Comment by FabianKramm** [comment] 2020-12-14 16:10
@ComaVN thanks for reporting this issue! Yes the problem is that ${DEVSPACE_RANDOM} will resolve to the same string in both cases. This will be fixed with the new version v5.6.0 which we release soon that introduces '#' instead of ${DEVSPACE_RANDOM}:
```yaml

version: v1beta9
images:
  foo:
    dockerfile: Dockerfile
    image: dockerregistry.example.com/comavn-devspace-parallel-build-foo
    tags:
      - dev-${DEVSPACE_USERNAME}-#####
    build:
      docker:
        useBuildKit: true
        options:
          buildArgs:
            timestamp: ${DEVSPACE_TIMESTAMP}
  bar:
    dockerfile: Dockerfile
    image: dockerregistry.example.com/comavn-devspace-parallel-build-bar
    tags:
      - dev-${DEVSPACE_USERNAME}-#####
    build:
      docker:
        useBuildKit: true
        options:
          buildArgs:
            timestamp: ${DEVSPACE_TIMESTAMP}
deployments:
  - name: dev
    kubectl:
      replaceImageTags: true
      manifests:
        - deployment.yaml
```

**Comment by ComaVN** [comment] 2020-12-14 19:05
Thank you for the quick response.

I'm not sure I understand it tho: how would this change how the parallel builds are done?

`$DEVSPACE_RANDOM` is only used in the Docker image tag, not the `buildArgs`, so I don't see what it has to do with docker image layer caching.

**Comment by FabianKramm** [comment] 2020-12-15 08:55
@ComaVN ah okay I see, you can set --build-sequential as a default via the `.env` file and the environment variable `DEVSPACE_DEV_FLAGS`

**Comment by ComaVN** [comment] 2020-12-15 10:50
Yes, that solves my problem, thanks. I prefer sequential builds anyway, because I like to see the docker build log, even when the build succeeds.

**Comment by FabianKramm** [comment] 2020-12-15 13:44
@ComaVN yes that is true. In future we want to add that devspace will print the logs also for parallel builds with a prefix in front of it, but this doesn't work currently unfortunately.

**Comment by deniseschannon** [comment] 2024-05-21 18:58
Closing due to inactivity and the version used. If you are still facing this issue with our latest DevSpace version, please open a new issue.

**Closed by deniseschannon** 2024-05-21 18:58 UTC
Labels: kind/bug, area/building-images, area/config
