### ISSUE TITLE
"name" field is required for v1 schemas which breaks backward compatibility with v5 of devspace

### ISSUE THREAD

**Issue by white-hat** [devspace-sh/devspace#2493] opened 2023-01-10 19:49 UTC
After upgrading to v6.2.4 from version v5.18.5 I can no longer import `v1beta11` version of `devspace.yaml` as a parent profile

For example, if my local `devspace.yaml` has the following lines

```
version: v1beta11
profiles:
  - name: my_local_profile
    parents:
      - profile: some_remote_profile
        source:
          path: ./parent
```

and `devspace.yaml` at `./parent` has the following structure

```
version: v1beta11
profiles:
  - name: some_remote_profile

...
```

I expect devspace v6.2.4 to successfully import this remote profile, instead I'm getting

```
fatal load parent profile some_remote_profile: you need to specify a name for your devspace.yaml
```

I could add `name: my_remote_devspace_config` to the remote profile, but that breaks it for users who still use v5.18.5

**Comment by 89luca89** [comment] 2023-02-21 14:41
Hi @white-hat

Regarding this, I think this is an incompatibility between v6 and v5
Older profile APIs (in this case v1beta11) are internally always converted to latest version (v2beta1) in memory, while using v6.

Now that `name` is obligatory for v6, and it does not depend on if you use v1beta11 or v2beta, but on the devspace version.
So this is intended behaviour for v6

**Comment by 89luca89** [comment] 2023-03-15 08:21
I'm closing this for now, as I didn't receive any feedback
Feel free to reopen if it is needed :+1:

**Closed by 89luca89** 2023-03-15 08:21 UTC
Labels: kind/bug, bug
