### ISSUE TITLE
/devspace/releases/assets/93304268: No such file or directory

### ISSUE THREAD

**Issue by cseas** [devspace-sh/devspace#2518] opened 2023-01-31 09:19 UTC
**What happened?**

I keep getting the below error after upgrading devspace with `devspace upgrade`.

> /usr/local/bin/devspace: line 1: url:[https://api.github.com/repos/devspace-sh/devspace/releases/assets/93304268:](https://api.github.com/repos/devspace-sh/devspace/releases/assets/93304268:) No such file or directory

**What did you expect to happen instead?**

No issues

**How can we reproduce the bug?** (as minimally and precisely as possible)

Upgrading devspace from 6.2.4 to 6.2.5

My devspace.yaml:

```
version: ...
...
```

**Local Environment:**

* DevSpace Version: 6.2.5
* Operating System: mac
* ARCH of the OS: AMD64 | ARM64 | i386
  **Kubernetes Cluster:**
* Cloud Provider: aws
* Kubernetes Version: v1.23.5

**Anything else we need to know?**

**Comment by 89luca89** [comment] 2023-01-31 09:49
Thanks @cseas  for reporting! We will take a look.

**Comment by igoooor** [comment] 2023-02-01 08:24
exact same problem here

**Comment by ecodrutzconteo** [comment] 2023-02-01 08:24
same problem after upgrading from 6.2.4 to 6.2.5 via self upgrade

**Comment by 89luca89** [comment] 2023-02-01 15:06
Hi, this is because of a bug in the upgrade, where a json file is downloaded instead of the binary
This is in fact a duplicate of #2516, we will continue the debug there :+1:

**Closed by 89luca89** 2023-02-01 15:06 UTC
Labels: kind/bug, bug
