### ISSUE TITLE
devspace ui shows a blank page

### ISSUE THREAD

**Issue by aetheon** [devspace-sh/devspace#2900] opened 2024-09-25 08:28 UTC
**What happened?**  
When running `devspace ui` it shows a blank page with the following javascript error:

```
Uncaught TypeError: o.render is not a function
    at Module.<anonymous> (main.a9eb55d6.js:1:539763)
    at i (main.a9eb55d6.js:1:110)
    at Object.<anonymous> (main.a9eb55d6.js:1:298982)
    at i (main.a9eb55d6.js:1:110)
    at main.a9eb55d6.js:1:903
    at main.a9eb55d6.js:1:913
```

Help appreciated on pointing out how to debug it and provide more info here.

**Local Environment:**  
- DevSpace Version: 6.3.12
- Operating System: mac
- ARCH of the OS: ARM64
**Kubernetes Cluster:**  
- Cloud Provider: aws
- Kubernetes Version: v1.30.2

**Comment by CKnoppas** [comment] 2024-09-25 10:01
duplicate of https://github.com/devspace-sh/devspace/issues/2899

**Comment by abhishekhugetech** [comment] 2024-09-27 07:45
I had the same issue changed version to `6.3.4` from latest and it's working

```
curl -L -o devspace 'https://github.com/loft-sh/devspace/releases/download/v6.3.4/devspace-linux-arm64' 
```

**Comment by deniseschannon** [comment] 2024-10-03 17:16
Closing as it's a duplicate of 2899

**Closed** 2024-10-03 17:16 UTC
Labels: kind/bug
